# Generated by Django 5.2.7 on 2025-11-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
