# Generated by Django 5.2.7 on 2025-10-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
    ]
