# Generated by Django 5.2.7 on 2025-10-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_course_options_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='course_preview/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_preview/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
