# Generated by Django 5.2.7 on 2025-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
