# Generated by Django 5.2.7 on 2025-12-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_payment_payment_url_payment_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
